<?php
return array(
    'username' => '/^[a-zA-Z0-9-_]*$/i' ,
    'username,' => '/^[a-zA-Z0-9-_,\s]*$/i' ,
    'password' => '/^[a-zA-Z0-9-_+?!$@#*\s]*$/i' ,
    'text' => '/^[a-zA-Z0-9آ-ی-.،,*:;()<>"+=@&?؟ !#\/_\s]*$/u' ,
    'number' => '/^[0-9]*$/u' ,
    'ip' => '/^[0-9.]*$/u' ,
    'alphabet' => '/^[a-zA-Z]*$/i' ,
    'alphabet-space' => '/^[a-zA-Z\s]*$/i' ,
    'alphabet-persian' => '/^[a-zA-Zآ-ی]*$/u' ,
    'alphabet-persian-space' => '/^[a-zA-Zآ-ی\s]*$/u' ,
    'md5' => '/^[a-z0-9]*$/i',
    'chat_id' => '/^[a-z0-9-._]*$/i',
    'chatroom_id' => '/^[A-Za-z0-9-._]*$/i',
    '/^[-a-z0-9]+\.[a-z][a-z]|biz|cat|com|edu|gov|int|mil|net|org|pro|tel|aero|arpa|asia|coop|info|jobs|mobi|name|museum|travel$/',
    'function_name' => '/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$/i',
    'email' => '/^[a-zA-Z0-9_.-@+,]*$/i',
    'cardNumber' => '/^[0-9]*$/u',
    'cvv2' => '/^[0-9]*$/u',
    'month' => '/^[0-9]*$/u',
    'year' => '/^[0-9]*$/u',
    'captcha' => '/^[0-9]*$/u',
    'invoice_key' => '/^[a-zA-Z0-9آ-ی-.،,*:;()<>"+=@&?؟ !#\/_\s]*$/u',
    'amount' => '/^[0-9]*$/u',
    'api_key' => '/^[a-zA-Z0-9آ-ی-.،,*:;()<>"+=@&?؟ !#\/_\s]*$/u',
);